-- V12가 integrations.provider의 열거형 CHECK를 없앤 것과 같은 이유로 checkpoints.provider도 없앤다.
-- V5가 만든 chk_checkpoints_provider(github/jira/slack)가 그대로 남아 있어, 새 provider의 checkpoint
-- upsert가 매번 제약 위반으로 실패했다(A9 — Discord 실기동에서 발견: publish는 성공하고 checkpoint
-- 쓰기만 터져 커서가 영원히 전진하지 못하는 상태로 이어졌다).
-- 유효성은 애플리케이션(CollectionProvider enum)이 보증한다.
--
-- V13~V15(linear/asana/clickup을 CHECK 허용 목록에 하나씩 추가)는 이 마이그레이션이 없애려는
-- 바로 그 트레드밀이다 — 병렬로 개발된 다른 브랜치가 독자적으로 추가했다. 그 세 마이그레이션이
-- 먼저 적용돼도 결과는 이 마이그레이션이 최종적으로 덮어써 무해하다(제약을 넓히다가 결국
-- 없앤다). 새 provider 추가 시 더 이상 이 파일 근처를 고칠 필요가 없다.
ALTER TABLE checkpoints DROP CONSTRAINT chk_checkpoints_provider;
