import type { ReactNode } from "react";
import { Link } from "react-router-dom";

import { GITHUB_AUTHORIZE_URL } from "@/api/auth";
import { useAuth } from "@/auth/AuthProvider";
import { useLandingLanguage, type Localized } from "@/components/landing/LandingLanguageProvider";
import { PATHS } from "@/routes";

const COPY: Localized<{
  whatHeading: string;
  whatBody: string;
  inSlackHeading: string;
  inSlackItem1: ReactNode;
  inSlackItem2: string;
  inSlackItem3: ReactNode;
  inSlackItem4: string;
  installHeading: string;
  installItem1: string;
  installItem2: string;
  installItem3: ReactNode;
  ctaStart: string;
  openApp: string;
  afterHeading: string;
  afterItem1: string;
  afterItem2: string;
  afterItem3: string;
  aboutHeading: string;
  aboutBody: string;
  relatedHeading: string;
  privacy: string;
  support: string;
  terms: string;
}> = {
  ko: {
    whatHeading: "무엇을 하나",
    whatBody:
      "whycode는 흩어진 커밋·PR·이슈·대화·문서를 하나의 그래프로 묶어, 코드가 왜 그렇게 바뀌었는지를 근거와 함께 답하는 서비스입니다. Slack 앱은 그 질문을 채널에서 바로 던지는 입구입니다 — 대시보드를 열지 않고도 같은 그래프에 묻습니다.",
    inSlackHeading: "Slack 안에서",
    inSlackItem1: (
      <>
        채널에서 <code>/why-code</code> 뒤에 질문을 적습니다. 예:{" "}
        <code>/why-code 결제 재시도 로직이 왜 바뀌었어?</code>
      </>
    ),
    inSlackItem2: "답은 명령을 실행한 본인에게만 보입니다. 채널의 다른 사람에게는 표시되지 않습니다.",
    inSlackItem3: (
      <>
        프로젝트가 여러 개면 <code>/why-code [프로젝트 이름] 질문</code>으로 지정합니다.{" "}
        <code>/why-code help</code>가 사용법을 다시 보여 줍니다.
      </>
    ),
    inSlackItem4:
      "커맨드는 워크스페이스를 연결한 whycode 계정의 사용자만 쓸 수 있습니다. 다른 사람이 실행하면 안내 메시지가 돌아옵니다.",
    installHeading: "설치",
    installItem1: "GitHub으로 로그인한 뒤 프로젝트를 만듭니다.",
    installItem2: "프로젝트의 소스 화면에서 Slack을 고르고, Slack 동의 화면에서 워크스페이스를 승인합니다.",
    installItem3: (
      <>
        채널에서 <code>/why-code</code>를 사용합니다.
      </>
    ),
    ctaStart: "GitHub으로 시작",
    openApp: "whycode 열기",
    afterHeading: "연결 후",
    afterItem1: "승인 직후 워크스페이스의 채널 대화 수집이 시작되고, 소스 화면에서 진행 상태를 볼 수 있습니다.",
    afterItem2: "수집이 그래프에 반영되면 커맨드 답변에 Slack 대화 맥락이 함께 쓰입니다.",
    afterItem3:
      "연결 해제는 소스 화면에서 합니다. 수집한 채널 메시지·스레드와 그 그래프가 삭제됩니다. Slack 워크스페이스에 설치된 앱은 남으므로 Slack 관리 화면에서 따로 제거합니다.",
    aboutHeading: "답변에 대하여",
    aboutBody:
      "답은 AI가 그래프를 근거로 만든 것이며, 사실과 다르거나 빠질 수 있습니다. 중요한 판단 전에 답에 인용된 원본을 확인하세요.",
    relatedHeading: "관련 문서",
    privacy: "개인정보처리방침",
    support: "지원",
    terms: "이용약관",
  },
  en: {
    whatHeading: "What it does",
    whatBody:
      "whycode ties scattered commits, PRs, issues, conversations, and documents into one graph, and answers why the code changed the way it did, with the evidence. The Slack app is a way to ask that question right from a channel — the same graph, without opening the dashboard.",
    inSlackHeading: "In Slack",
    inSlackItem1: (
      <>
        Type your question after <code>/why-code</code> in a channel. For example:{" "}
        <code>/why-code why did the payment retry logic change?</code>
      </>
    ),
    inSlackItem2: "The answer is shown only to you. Nobody else in the channel sees it.",
    inSlackItem3: (
      <>
        With several projects, pick one with <code>/why-code [project name] question</code>.{" "}
        <code>/why-code help</code> shows the usage again.
      </>
    ),
    inSlackItem4:
      "The command works for the Slack user whose whycode account connected the workspace. Anyone else gets a short notice instead.",
    installHeading: "Install",
    installItem1: "Sign in with GitHub and create a project.",
    installItem2: "In the project's Sources, choose Slack and approve the workspace on Slack's consent screen.",
    installItem3: (
      <>
        Use <code>/why-code</code> in a channel.
      </>
    ),
    ctaStart: "Start with GitHub",
    openApp: "Open whycode",
    afterHeading: "After connecting",
    afterItem1: "Right after approval, whycode starts collecting channel conversations from the workspace; Sources shows the progress.",
    afterItem2: "Once collected into the graph, Slack context is used in command answers.",
    afterItem3:
      "Disconnect from Sources. Collected channel messages, threads, and their graph are deleted. The app itself stays installed in the Slack workspace, so remove it from Slack's admin screen separately.",
    aboutHeading: "About the answers",
    aboutBody: "Answers are generated by AI from the graph, and may be wrong or incomplete. Check the cited originals before you rely on them.",
    relatedHeading: "Related",
    privacy: "Privacy Policy",
    support: "Support",
    terms: "Terms of Service",
  },
};

// Slack 본문 — 조 번호 없는 짧은 산문(SupportBody와 같은 패턴). LegalLayout 안에서 렌더되므로
// 언어는 Provider에서 읽는다. 설치 절의 실행 버튼은 FinalCtaSection의 인증 상태 분기를 그대로
// 복제한 것이다(공용 컴포넌트로 뽑기엔 두 곳뿐).
export function SlackBody() {
  const { lang } = useLandingLanguage();
  const { status } = useAuth();
  const t = COPY[lang];

  return (
    <>
      <section className="lp-legal-section">
        <h2 className="lp-legal-heading">{t.whatHeading}</h2>
        <p>{t.whatBody}</p>
      </section>

      <section className="lp-legal-section">
        <h2 className="lp-legal-heading">{t.inSlackHeading}</h2>
        <ul>
          <li>{t.inSlackItem1}</li>
          <li>{t.inSlackItem2}</li>
          <li>{t.inSlackItem3}</li>
          <li>{t.inSlackItem4}</li>
        </ul>
      </section>

      <section className="lp-legal-section">
        <h2 className="lp-legal-heading">{t.installHeading}</h2>
        <ol>
          <li>{t.installItem1}</li>
          <li>{t.installItem2}</li>
          <li>{t.installItem3}</li>
        </ol>
        <p>
          {status === "authenticated" ? (
            <Link className="lp-btn lp-btn--primary" to={PATHS.root}>{t.openApp}</Link>
          ) : (
            <a className="lp-btn lp-btn--primary" href={GITHUB_AUTHORIZE_URL}>{t.ctaStart}</a>
          )}
        </p>
      </section>

      <section className="lp-legal-section">
        <h2 className="lp-legal-heading">{t.afterHeading}</h2>
        <ul>
          <li>{t.afterItem1}</li>
          <li>{t.afterItem2}</li>
          <li>{t.afterItem3}</li>
        </ul>
      </section>

      <section className="lp-legal-section">
        <h2 className="lp-legal-heading">{t.aboutHeading}</h2>
        <p className="lp-legal-notice">{t.aboutBody}</p>
      </section>

      <section className="lp-legal-section">
        <h2 className="lp-legal-heading">{t.relatedHeading}</h2>
        <ul>
          <li>
            <Link to={`${PATHS.privacy}#slack`}>{t.privacy}</Link>
          </li>
          <li>
            <Link to={PATHS.support}>{t.support}</Link>
          </li>
          <li>
            <Link to={PATHS.terms}>{t.terms}</Link>
          </li>
        </ul>
      </section>
    </>
  );
}
