import { Link } from "react-router-dom";

import { useLandingLanguage, type Localized } from "@/components/landing/LandingLanguageProvider";
import { PATHS } from "@/routes";

const COPY: Localized<{
  headline: string;
  notice: string;
  privacy: string;
  support: string;
}> = {
  ko: {
    headline: "Slack 안에서 묻는다.",
    notice:
      "답은 AI가 그래프를 근거로 만든 것이며, 사실과 다르거나 빠질 수 있습니다. 중요한 판단 전에 답에 인용된 원본을 확인하세요.",
    privacy: "개인정보처리방침",
    support: "지원",
  },
  en: {
    headline: "Ask from inside Slack.",
    notice:
      "Answers are generated by AI from the graph, and may be wrong or incomplete. Check the cited originals before you rely on them.",
    privacy: "Privacy Policy",
    support: "Support",
  },
};

const STEPS: Array<{ num: string; title: Localized<string>; body: Localized<string> }> = [
  {
    num: "01",
    title: { ko: "시작", en: "Start" },
    body: {
      ko: "GitHub으로 로그인한 뒤 프로젝트를 만듭니다.",
      en: "Sign in with GitHub and create a project.",
    },
  },
  {
    num: "02",
    title: { ko: "연결", en: "Connect" },
    body: {
      ko: "소스에서 Slack 워크스페이스를 고릅니다.",
      en: "Choose a Slack workspace in Sources.",
    },
  },
  {
    num: "03",
    title: { ko: "질문", en: "Ask" },
    body: {
      ko: "채널에서 커맨드 뒤에 질문을 적습니다.",
      en: "Type your question after the command in a channel.",
    },
  },
];

// Slack 앱 절 — 마켓플레이스·Installation landing page가 가리킬 공개 설명.
// 형식은 타이포 + 세로 스텝(작동 방식의 미니 그래프 3단과 겹치지 않게).
// id="in-slack" — /privacy#slack 과 페이지가 달라 충돌하지 않고, 랜딩 안 해시로 바로 착지한다.
export function SlackAppSection() {
  const { lang } = useLandingLanguage();
  const t = COPY[lang];

  return (
    <section className="lp-slack" id="in-slack">
      <div className="lp-slack-inner">
        <div className="lp-slack-header">
          <p className="lp-slack-eyebrow">IN SLACK</p>
          <h2 className="lp-slack-headline">{t.headline}</h2>
        </div>
        <p className="lp-slack-body">
          {lang === "ko" ? (
            <>
              채널에서 <code className="lp-slack-cmd">/why-code</code> 뒤에 질문을 붙이면,
              연결된 그래프에서 답을 찾아 본인에게만 보여 줍니다. 설치는 Slack이 아니라
              GitHub 로그인으로 시작합니다 — 프로젝트 소스에서 워크스페이스를 연결한 뒤에
              커맨드가 살아납니다.
            </>
          ) : (
            <>
              Type a question after <code className="lp-slack-cmd">/why-code</code> in a
              channel; whycode looks it up on the connected graph and replies only to you.
              Install starts with GitHub, not Slack — connect a workspace in Sources, then
              the command comes alive.
            </>
          )}
        </p>
        <ol className="lp-slack-steps">
          {STEPS.map((step) => (
            <li className="lp-slack-step" key={step.num}>
              <h3 className="lp-slack-step-title">
                <span className="lp-slack-step-num">{step.num} /</span>
                <span className="lp-slack-step-name">{step.title[lang]}</span>
              </h3>
              <p className="lp-slack-step-body">{step.body[lang]}</p>
            </li>
          ))}
        </ol>
        <p className="lp-slack-notice">{t.notice}</p>
        <p className="lp-slack-links">
          <Link className="lp-slack-link" to={`${PATHS.privacy}#slack`}>
            {t.privacy}
          </Link>
          <Link className="lp-slack-link" to={PATHS.support}>
            {t.support}
          </Link>
        </p>
      </div>
    </section>
  );
}
